apiVersion: v1
kind: ServiceAccount
metadata:
  name: supabase-secrets-sa
  namespace: supabase
  annotations:
    # Replace the ARN below with the IAM role created for the CSI provider or IRSA role
    eks.amazonaws.com/role-arn: arn:aws:iam::998284843362:role/dev-supabase-csi-role
